// Generated by scripts/generate-fact-cache-revision.mjs. Do not edit.
// Digest of packages/compiler/src, so any change to how facts are derived
// invalidates every persisted theme fact cache.
export const THEME_FACT_CACHE_REVISION = "theme-facts-9dd80d6cf556a7bf";
