// Generated by scripts/generate-fact-cache-revision.mjs. Do not edit.
// Digest of compiler/source adapters and grammar sources, so fact changes
// invalidates every persisted theme fact cache.
export const THEME_FACT_CACHE_REVISION = "theme-facts-9d540250b5d48e3c";
