import assert from "node:assert/strict";
import test from "node:test";
import {
	analyzeMetafields,
	analyzeNazareTheme,
	collectMetafieldDefinitions,
	collectMetafieldReads,
	inspectNazareTheme,
	joinMetafieldReads,
} from "../dist/index.js";

const issues = (files) => analyzeNazareTheme(files).issues;
const hasIssue = (files, code) =>
	issues(files).some((issue) => issue.code === code);

test("metafield definition and read collection compose deterministically", () => {
	const snapshot = {
		path: ".shopify/metafields.json",
		contents: JSON.stringify({
			definitions: [{ owner: "product", namespace: "custom", key: "subtitle" }],
		}),
	};
	const accesses = [
		{
			id: "access:subtitle",
			fromPath: "sections/main.liquid",
			object: "product",
			propertyPath: "metafields.custom.subtitle",
			expression: "product.metafields.custom.subtitle",
			origin: "liquid",
		},
	];
	const definitions = collectMetafieldDefinitions(snapshot);
	const reads = joinMetafieldReads(
		definitions.definitions,
		collectMetafieldReads(accesses),
	);
	const analysis = analyzeMetafields(snapshot, accesses);
	assert.deepEqual(definitions.definitions, analysis.definitions);
	assert.deepEqual(reads, analysis.reads);
	assert.equal(reads[0].definitionId, "metafield:product:custom:subtitle");
});

test("theme analysis cache reuses unchanged files and invalidates edits", () => {
	const cache = { version: 1, entries: {} };
	const files = [
		{ path: "snippets/card.liquid", contents: "{{ product.title }}" },
		{ path: "locales/en.json", contents: '{"card":{"title":"Card"}}' },
	];
	const first = analyzeNazareTheme(files, { cache });
	const cachedSnippet = cache.entries["snippets/card.liquid"];
	const cachedLocale = cache.entries["locales/en.json"];
	assert.ok(cachedSnippet);
	assert.ok(cachedLocale);

	const second = analyzeNazareTheme(
		[
			files[0],
			{ path: "locales/en.json", contents: '{"card":{"title":"Tile"}}' },
		],
		{ cache },
	);
	assert.strictEqual(cache.entries["snippets/card.liquid"], cachedSnippet);
	assert.notStrictEqual(cache.entries["locales/en.json"], cachedLocale);
	assert.deepEqual(second.ir.variableReads, first.ir.variableReads);

	analyzeNazareTheme([files[0]], { cache });
	assert.equal(cache.entries["locales/en.json"], undefined);
});

test("theme input validation rejects invalid JSON shapes and unsafe paths", () => {
	for (const [path, contents, code] of [
		["config/settings_schema.json", "{}", "THEME_SETTINGS_SCHEMA_INVALID_ROOT"],
		["config/settings_data.json", "[]", "THEME_SETTINGS_DATA_INVALID_ROOT"],
		[
			"templates/index.json",
			'{"sections":[]}',
			"THEME_TEMPLATE_INVALID_SECTIONS",
		],
		["locales/en.json", "[]", "THEME_LOCALE_INVALID_ROOT"],
	]) {
		assert.equal(hasIssue([{ path, contents }], code), true, path);
	}

	for (const path of [
		"",
		".",
		"C:/theme/file.liquid",
		"a/./b.liquid",
		"a\u0000b.liquid",
	]) {
		assert.equal(
			hasIssue([{ path, contents: "" }], "THEME_UNSAFE_PATH"),
			true,
			JSON.stringify(path),
		);
	}
});

test("theme analysis accepts Shopify-generated JSON preambles", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "templates/index.json",
			contents:
				"/*\n * IMPORTANT: generated by Shopify\n */\n" +
				JSON.stringify({ sections: { hero: { type: "hero" } } }),
		},
		{ path: "sections/hero.liquid", contents: "Hero" },
	]);
	assert.equal(
		analysis.issues.some((issue) => issue.code === "THEME_JSON_PARSE_ERROR"),
		false,
	);
	assert.equal(analysis.ir.sectionInstances.length, 1);
});

test("theme analysis reports duplicate, ambiguous, and broken schema inputs", () => {
	assert.equal(
		hasIssue(
			[
				{ path: "./sections/main.liquid", contents: "one" },
				{ path: "sections/main.liquid", contents: "two" },
			],
			"THEME_DUPLICATE_NORMALIZED_PATH",
		),
		true,
	);

	const ambiguous = [
		{ path: "sections/main.liquid", contents: `{% render 'button' %}` },
		{ path: "snippets/button.liquid", contents: "plain" },
		{ path: "components/button.nz.liquid", contents: "<button>NZ</button>" },
	];
	assert.equal(hasIssue(ambiguous, "THEME_DUPLICATE_DECLARATION"), true);
	assert.equal(hasIssue(ambiguous, "THEME_AMBIGUOUS_REFERENCE"), true);
	assert.equal(hasIssue(ambiguous, "THEME_UNRESOLVED_REFERENCE"), false);

	assert.equal(
		hasIssue(
			[
				{
					path: "sections/broken.liquid",
					contents: `{% schema %}{ not json }{% endschema %}`,
				},
			],
			"THEME_SCHEMA_JSON_INVALID",
		),
		true,
	);
});

test("theme input inference handles render arguments and Liquid scope", () => {
	assert.equal(
		hasIssue(
			[
				{ path: "sections/card.liquid", contents: `{% render 'price' %}` },
				{
					path: "snippets/price.liquid",
					contents: `{{ card_product.price }}`,
				},
			],
			"THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
	assert.equal(
		hasIssue(
			[
				{
					path: "sections/card.liquid",
					contents: `{% render 'price', card_product: product, unused: product %}`,
				},
				{
					path: "snippets/price.liquid",
					contents: `{{ card_product.price }}`,
				},
			],
			"THEME_RENDER_ARGUMENT_UNKNOWN",
		),
		true,
	);
	assert.equal(
		hasIssue(
			[
				{
					path: "sections/main.liquid",
					contents: `{% render 'price', card_product: product %}\n{% render 'price', card_product: featured_product %}\n{% render 'price' %}`,
				},
				{
					path: "snippets/price.liquid",
					contents: `{{ card_product.price }}`,
				},
			],
			"THEME_RENDER_ARGUMENT_INCONSISTENT",
		),
		true,
	);
	assert.equal(
		hasIssue(
			[
				{
					path: "sections/main.liquid",
					contents: `{% render 'price', card_product: product %}\n{% render 'price', card_product: featured_product %}\n{% render 'price' %}`,
				},
				{
					path: "snippets/price.liquid",
					contents: `{{ card_product.price }}`,
				},
			],
			"THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);

	assert.equal(
		hasIssue(
			[
				{ path: "sections/main.liquid", contents: `{% render 'price' %}` },
				{
					path: "snippets/price.liquid",
					contents: `{% if card_product %}{{ card_product.price }}{% endif %}`,
				},
			],
			"THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
	assert.equal(
		hasIssue(
			[
				{ path: "sections/main.liquid", contents: `{% render 'price' %}` },
				{
					path: "snippets/price.liquid",
					contents:
						"{% if card_product %}{{ card_product.price }}{% endif %}{{ card_product.title }}",
				},
			],
			"THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
	assert.equal(
		hasIssue(
			[
				{ path: "sections/main.liquid", contents: `{% render 'local' %}` },
				{
					path: "snippets/local.liquid",
					contents: `{% assign label = 'Hi' %}{{ label }}`,
				},
			],
			"THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
});

test("declared required inputs diagnose every omission without call-site heuristics", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'price' %}\n{% render 'price', card_product: product %}`,
		},
		{
			path: "snippets/price.liquid",
			contents: [
				"{% doc %}",
				"  @param {product} card_product - Product to render",
				"{% enddoc %}",
				"{{ card_product.price }}",
			].join("\n"),
		},
	]);
	const missing = analysis.issues.filter(
		(issue) => issue.code === "THEME_RENDER_ARGUMENT_MISSING",
	);

	assert.equal(missing.length, 1);
	assert.match(missing[0].message, /required declared input card_product/);
});

test("ambient Shopify context remains unknown rather than required", () => {
	const analysis = analyzeNazareTheme([
		{ path: "sections/main.liquid", contents: `{% render 'price' %}` },
		{ path: "snippets/price.liquid", contents: `{{ product.price }}` },
	]);
	assert.equal(
		analysis.issues.some(
			(issue) => issue.code === "THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
	assert.deepEqual(analysis.ir.expectedInputs, [
		{
			id: "expected-input:snippets/price.liquid:product",
			path: "snippets/price.liquid",
			name: "product",
			required: false,
			requirement: "unknown",
			provenance: "inferred",
			inferredRequirement: "unknown",
			declaredType: undefined,
			origin: "ambientShopifyContext",
			propertyPaths: ["price"],
			evidenceIds: ["data-access:snippets/price.liquid:product.price:1:4-1:17"],
		},
	]);
});

test("render aliases preserve input and Shopify property provenance", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'price' with product as card_product %}`,
		},
		{
			path: "snippets/price.liquid",
			contents: `{% assign displayed = card_product %}{{ displayed.price }}`,
		},
	]);
	assert.equal(
		analysis.issues.some(
			(issue) =>
				issue.code === "THEME_RENDER_ARGUMENT_MISSING" ||
				issue.code === "LIQUID_UNSCANNED_SETTINGS_EXPRESSION",
		),
		false,
	);
	assert.equal(analysis.ir.renderArguments[0]?.argumentName, "card_product");
	assert.ok(
		analysis.ir.dataAccesses.some(
			(access) =>
				access.fromPath === "snippets/price.liquid" &&
				access.expression === "product.price" &&
				access.origin === "renderArgument",
		),
	);
});

test("render for bindings preserve collection element type", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'price' for collection.products as card_product %}`,
		},
		{ path: "snippets/price.liquid", contents: `{{ card_product.price }}` },
	]);
	assert.ok(
		analysis.ir.dataAccesses.some(
			(access) =>
				access.fromPath === "snippets/price.liquid" &&
				access.expression === "product.price" &&
				access.origin === "renderArgument",
		),
	);
});

test("theme input inference respects include and lexical scopes", () => {
	const includeFiles = [
		{ path: "sections/main.liquid", contents: "{% include 'card' %}" },
		{ path: "snippets/card.liquid", contents: "{{ product.title }}" },
	];
	assert.equal(hasIssue(includeFiles, "THEME_RENDER_ARGUMENT_MISSING"), false);

	const loopAnalysis = analyzeNazareTheme([
		{ path: "sections/main.liquid", contents: `{% render 'loop' %}` },
		{
			path: "snippets/loop.liquid",
			contents:
				"{% for item in collection.products %}{{ item.title }}{% endfor %}{{ item.title }}",
		},
	]);
	assert.equal(
		loopAnalysis.ir.expectedInputs.some(
			(input) => input.name === "item" && input.required,
		),
		true,
	);
	const conditionalAnalysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'conditional' %}`,
		},
		{
			path: "snippets/conditional.liquid",
			contents:
				"{% if product %}\n{% assign label = product.title %}\n{% endif %}\n{{ label }}",
		},
	]);
	assert.equal(
		conditionalAnalysis.ir.expectedInputs.some(
			(input) => input.name === "label" && input.required,
		),
		true,
	);
});

test("branch-local assignments and captures are not inferred as inputs", () => {
	const sameBranch = analyzeNazareTheme([
		{
			path: "snippets/image.liquid",
			contents:
				"{% if image %}{% assign width = image.width %}{% capture srcset %}{{ image | image_url }}{% endcapture %}{{ width }}{{ srcset }}{% endif %}",
		},
	]);
	assert.deepEqual(
		sameBranch.ir.expectedInputs.map((input) => input.name),
		["image"],
	);

	const siblingBranch = analyzeNazareTheme([
		{
			path: "snippets/image.liquid",
			contents:
				"{% if image %}{% assign width = image.width %}{% else %}{{ width }}{% endif %}",
		},
	]);
	assert.ok(
		siblingBranch.ir.expectedInputs.some((input) => input.name === "width"),
	);

	const exhaustiveBranches = analyzeNazareTheme([
		{
			path: "snippets/exhaustive.liquid",
			contents:
				"{% if mode %}{% assign label = 'a' %}{% else %}{% capture label %}b{% endcapture %}{% endif %}{{ label }}",
		},
	]);
	assert.equal(
		exhaustiveBranches.ir.expectedInputs.some(
			(input) => input.name === "label",
		),
		false,
	);

	const branchConditions = analyzeNazareTheme([
		{
			path: "snippets/conditional-inputs.liquid",
			contents:
				"{% if primary %}{{ primary }}{% elsif fallback %}{{ fallback }}{% unless hidden %}visible{% endunless %}{% endif %}",
		},
	]);
	assert.deepEqual(
		branchConditions.ir.expectedInputs.map((input) => [
			input.name,
			input.requirement,
		]),
		[
			["fallback", "optional"],
			["hidden", "optional"],
			["primary", "optional"],
		],
	);
});

test("default filters and guarded aliases infer optional inputs", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "snippets/defaults.liquid",
			contents:
				"{% assign guarded_local = guarded %}{% if guarded_local != blank %}{{ guarded_local }}{% endif %}{% assign default_local = defaulted | default: 'value' %}{{ default_local }}{% assign fallback_local = fallback %}{% if fallback_local == blank %}{% assign fallback_local = 'value' %}{% endif %}{{ fallback_local }}{% case color %}{% when 'blue' %}blue{% endcase %}{{ output_default | default: 'value' }}{% assign required_local = required %}{{ required_local }}",
		},
	]);
	assert.deepEqual(
		analysis.ir.expectedInputs.map((input) => [input.name, input.requirement]),
		[
			["color", "optional"],
			["defaulted", "optional"],
			["fallback", "optional"],
			["guarded", "optional"],
			["output_default", "optional"],
			["required", "required"],
		],
	);
});

test("forwarding-only inputs remain unknown without a downstream contract", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'media' %}`,
		},
		{
			path: "snippets/media.liquid",
			contents: `{% render 'image', priority: priority %}`,
		},
		{
			path: "snippets/image.liquid",
			contents: `{{ priority }}`,
		},
	]);
	assert.deepEqual(
		analysis.ir.expectedInputs.find(
			(input) =>
				input.path === "snippets/media.liquid" && input.name === "priority",
		)?.requirement,
		"unknown",
	);
	assert.equal(
		analysis.issues.some(
			(issue) => issue.code === "THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
});

test("conditional aliases preserve property flow only inside their branch", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'price', card_product: product %}`,
		},
		{
			path: "snippets/price.liquid",
			contents:
				"{% if card_product %}{% assign displayed = card_product %}{{ displayed.price }}{% endif %}",
		},
	]);
	assert.ok(
		analysis.ir.dataAccesses.some(
			(access) =>
				access.fromPath === "snippets/price.liquid" &&
				access.expression === "product.price",
		),
	);
});

test("theme schema validation rejects malformed and duplicate definitions", () => {
	assert.equal(
		hasIssue(
			[
				{
					path: "sections/main.liquid",
					contents: '{% schema %}{"settings":{}}{% endschema %}',
				},
			],
			"THEME_SCHEMA_INVALID_SETTINGS",
		),
		true,
	);
	assert.equal(
		hasIssue(
			[
				{
					path: "sections/main.liquid",
					contents:
						'{% schema %}{"settings":[{"type":"text","id":"x"},{"type":"text","id":"x"}]}{% endschema %}',
				},
			],
			"THEME_SCHEMA_DUPLICATE_SETTING_ID",
		),
		true,
	);
});

test("imported render aliases remain resolved", () => {
	const imported = analyzeNazareTheme([
		{
			path: "entry.nz.liquid",
			contents:
				'{% import Child from "./child.nz.liquid" %}<div>{% render Child {} %}</div>',
		},
		{ path: "child.nz.liquid", contents: "<span>child</span>" },
	]);
	assert.equal(
		imported.issues.some(
			(issue) => issue.code === "THEME_UNRESOLVED_REFERENCE",
		),
		false,
	);
});

test("theme and unambiguous block setting reads resolve", () => {
	const graph = inspectNazareTheme([
		{
			path: "config/settings_schema.json",
			contents: '[{"settings":[{"type":"text","id":"brand"}]}]',
		},
		{
			path: "sections/main.liquid",
			contents:
				'{{ settings.brand }} {{ block.settings.heading }}{% schema %}{"blocks":[{"type":"feature","settings":[{"type":"text","id":"heading"}]}]}{% endschema %}',
		},
	]);
	assert.equal(
		graph.issues.some(
			(issue) =>
				issue.code === "THEME_UNRESOLVED_SETTING_READ" ||
				issue.code === "THEME_AMBIGUOUS_SETTING_READ",
		),
		false,
	);
});

test("ambiguous block setting reads expose candidates and diagnostics", () => {
	const graph = inspectNazareTheme([
		{
			path: "sections/main.liquid",
			contents:
				'{{ block.settings.heading }}{% schema %}{"blocks":[{"type":"a","settings":[{"type":"text","id":"heading"}]},{"type":"b","settings":[{"type":"text","id":"heading"}]}]}{% endschema %}',
		},
	]);
	assert.equal(
		graph.issues.some((issue) => issue.code === "THEME_AMBIGUOUS_SETTING_READ"),
		true,
	);
});

test("theme source facts preserve Liquid inside large HTML raw-text bodies", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "snippets/styles.liquid",
			contents: `<style>${".generated{color:red}".repeat(1_000)}.live{color:{{ product.vendor }}}</style>`,
		},
	]);
	assert.ok(
		analysis.ir.dataAccesses.some(
			(access) => access.expression === "product.vendor",
		),
	);
});

test("theme source facts ignore non-Liquid regions and keep repeated references distinct", () => {
	const quiet = analyzeNazareTheme([
		{
			path: "snippets/quiet.liquid",
			contents: `{% comment %}{{ product.price }}{% endcomment %}\n<!-- cart.items -->\nplain text mentioning product.title`,
		},
		{
			path: "components/widget.nz.liquid",
			contents: `<div ref="root"></div>\n{% script %}\nconst n = cart.items.length;\nexport default island(() => {});\n{% endscript %}`,
		},
	]);
	assert.deepEqual(quiet.ir.dataAccesses, []);
	assert.deepEqual(quiet.ir.capabilities, []);

	const repeated = analyzeNazareTheme([
		{ path: "locales/en.json", contents: '{"key":"value"}' },
		{ path: "locales/fr.json", contents: '{"key":"valeur"}' },
		{
			path: "snippets/repeated.liquid",
			contents: "{{ 'key' | t }} {{ 'key' | t }}",
		},
	]);
	assert.equal(
		repeated.issues.some(
			(issue) => issue.code === "THEME_UNRESOLVED_LOCALE_KEY",
		),
		false,
	);
	assert.equal(repeated.ir.localeKeys.length, 1);
	assert.equal(repeated.ir.localeTranslations.length, 2);
	assert.deepEqual(
		repeated.ir.localeReferences.map(
			(reference) => reference.resolvedLocaleKeyIds,
		),
		[["locale-key:key"], ["locale-key:key"]],
	);
});

test("theme analysis excludes configured globs and reports every excluded file", () => {
	const files = [
		{ path: "snippets/card.liquid", contents: "{{ product.title }}" },
		{
			path: "snippets/reploChunk.abc.0.liquid",
			contents: "<div>generated</div>",
		},
		{
			path: "snippets/reploChunk.abc.1.liquid",
			contents: "{{ product.price }}",
		},
	];

	const analysis = analyzeNazareTheme(files, {
		exclude: ["snippets/reploChunk.*.liquid"],
	});
	const excluded = analysis.issues.filter(
		(issue) => issue.code === "THEME_FILE_EXCLUDED",
	);

	assert.equal(excluded.length, 2);
	assert.deepEqual(excluded.map((issue) => issue.span.file).sort(), [
		"snippets/reploChunk.abc.0.liquid",
		"snippets/reploChunk.abc.1.liquid",
	]);
	assert.equal(
		excluded.every((issue) => issue.severity === "info"),
		true,
	);
	assert.equal(
		analysis.issues.some(
			(issue) =>
				issue.span?.file === "snippets/card.liquid" &&
				issue.code === "THEME_FILE_EXCLUDED",
		),
		false,
	);
});

test("theme analysis keeps every file when no exclusions are configured", () => {
	const files = [
		{ path: "snippets/card.liquid", contents: "{{ product.title }}" },
	];

	assert.equal(hasIssue(files, "THEME_FILE_EXCLUDED"), false);
	assert.equal(
		analyzeNazareTheme(files, { exclude: [] }).issues.some(
			(issue) => issue.code === "THEME_FILE_EXCLUDED",
		),
		false,
	);
});

test("excluded files leave no nodes in the inspected graph", () => {
	const files = [
		{
			path: "sections/main.liquid",
			contents: "{% render 'reploChunk.abc.0' %}",
		},
		{ path: "snippets/reploChunk.abc.0.liquid", contents: "<div>x</div>" },
	];

	const graph = inspectNazareTheme(files, {
		exclude: ["snippets/reploChunk.**"],
	});

	assert.equal(
		graph.nodes.some((node) => node.id.includes("reploChunk.abc.0.liquid")),
		false,
	);
	assert.equal(
		graph.issues.some((issue) => issue.code === "THEME_FILE_EXCLUDED"),
		true,
	);
});

test("theme exclusion globs match segments, wildcards, and single characters", async () => {
	const { matchesThemeGlob } = await import("../dist/index.js");

	assert.equal(
		matchesThemeGlob("snippets/a.liquid", "snippets/*.liquid"),
		true,
	);
	assert.equal(
		matchesThemeGlob("snippets/deep/a.liquid", "snippets/*.liquid"),
		false,
	);
	assert.equal(
		matchesThemeGlob("snippets/deep/a.liquid", "snippets/**/*.liquid"),
		true,
	);
	assert.equal(
		matchesThemeGlob("snippets/a.liquid", "snippets/**/*.liquid"),
		true,
	);
	assert.equal(
		matchesThemeGlob("snippets/ab.liquid", "snippets/a?.liquid"),
		true,
	);
	assert.equal(
		matchesThemeGlob("snippets/a.liquid", "snippets/a?.liquid"),
		false,
	);
	assert.equal(
		matchesThemeGlob("./snippets/a.liquid", "snippets/a.liquid"),
		true,
	);
	assert.equal(
		matchesThemeGlob("snippets/axliquid", "snippets/a.liquid"),
		false,
	);
});

test("a guard stored in a derived boolean keeps the guarded input optional", () => {
	// Themes test a value once and branch on the boolean afterwards. The later
	// reads are guarded just as directly as `{% if image != blank %}` would be.
	const contents = [
		"{%- if responsive_image != blank -%}",
		"{% assign has_image = true %}",
		"{%- else -%}",
		"{% assign has_image = false %}",
		"{%- endif -%}",
		'{%- if has_image == true -%}<img src="{{ responsive_image }}">{%- endif -%}',
	].join("");
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-img.liquid", contents },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "responsive_image",
	);

	assert.equal(input?.requirement, "optional");
});

test("only boolean literals become guard proxies", () => {
	// An ordinary assignment inside a conditional must never turn a later
	// condition into a guard, or any assignment would launder a required input.
	const contents = [
		"{%- if img != blank -%}{% assign label = img.alt %}{%- endif -%}",
		"{%- if label -%}<i>{{ img }}</i>{%- endif -%}",
	].join("");
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-label.liquid", contents },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "img",
	);

	assert.equal(input?.requirement, "required");
});

test("an input defaulted by unless-assign is optional without a prior alias", () => {
	// `{% unless x != blank %}{% assign x = fallback %}{% endunless %}` states
	// that the caller may omit x, exactly like the `default` filter does.
	const contents =
		'{%- unless alt != blank -%}{% assign alt = image.alt %}{%- endunless -%}<img alt="{{ alt }}">';
	const analysis = analyzeNazareTheme([
		{ path: "snippets/lazy-image.liquid", contents },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "alt",
	);

	assert.equal(input?.requirement, "optional");
});

test("an unguarded, undefaulted input stays required", () => {
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-plain.liquid", contents: "<i>{{ card_title }}</i>" },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "card_title",
	);

	assert.equal(input?.requirement, "required");
});

const DOCUMENTED_CARD = [
	"{% doc %}",
	"  @param {product} product - The product",
	"  @param {string} [class] - Extra classes",
	"  @param {string} [ghost] - Never read",
	"{% enddoc %}",
	"<div class='{{ class }}'>{{ product.title }}{{ undocumented_input }}</div>",
].join("\n");

test("a declared @param overrides inferred requiredness and records both", () => {
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-card.liquid", contents: DOCUMENTED_CARD },
	]);
	const byName = new Map(
		analysis.ir.expectedInputs.map((input) => [input.name, input]),
	);

	// `product` is a Liquid global, so inference can only call it unknown; the
	// author declaring it a parameter is what makes it required.
	assert.equal(byName.get("product")?.requirement, "required");
	assert.equal(byName.get("product")?.provenance, "declared");
	assert.equal(byName.get("product")?.inferredRequirement, "unknown");
	assert.equal(byName.get("product")?.declaredType, "product");

	// An unguarded read would infer required; the declaration says otherwise.
	assert.equal(byName.get("class")?.requirement, "optional");
	assert.equal(byName.get("class")?.provenance, "declared");
	assert.equal(byName.get("class")?.inferredRequirement, "required");

	// An undeclared input keeps inferring, and says so.
	assert.equal(byName.get("undocumented_input")?.provenance, "inferred");
});

test("a declared param with no read is still part of the interface", () => {
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-card.liquid", contents: DOCUMENTED_CARD },
	]);
	const ghost = analysis.ir.expectedInputs.find(
		(input) => input.name === "ghost",
	);

	assert.equal(ghost?.origin, "docParam");
	assert.equal(ghost?.requirement, "optional");
	assert.ok(
		ghost?.evidenceIds.length > 0,
		"declared inputs cite their doc span",
	);
});

test("doc contract disagreements are reported as information, not defects", () => {
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-card.liquid", contents: DOCUMENTED_CARD },
	]);
	const codes = analysis.issues
		.filter((issue) => issue.code.startsWith("THEME_DOC_"))
		.map((issue) => `${issue.code}:${issue.severity}`)
		.sort();

	assert.deepEqual(codes, [
		"THEME_DOC_PARAM_UNDECLARED:info",
		"THEME_DOC_PARAM_UNGUARDED:info",
	]);
	// Liquid renders an absent variable as empty rather than raising, so none of
	// these may be a warning: an unguarded optional read is a valid idiom.
	assert.equal(
		analysis.issues.some(
			(issue) =>
				issue.code.startsWith("THEME_DOC_") && issue.severity !== "info",
		),
		false,
	);
});

test("undocumented files are unaffected by doc contracts", () => {
	const analysis = analyzeNazareTheme([
		{ path: "snippets/c-plain.liquid", contents: "<i>{{ card_title }}</i>" },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "card_title",
	);

	assert.equal(input?.provenance, "inferred");
	assert.equal(input?.requirement, "required");
	assert.equal(
		analysis.issues.some((issue) => issue.code.startsWith("THEME_DOC_")),
		false,
	);
});

test("an argument a caller passes by name is an input, not ambient context", () => {
	// From inside the file `product.title` could be page context; the caller
	// writing `product:` is what says it is a parameter.
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'card', product: featured %}`,
		},
		{ path: "snippets/card.liquid", contents: "{{ product.title }}" },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "product",
	);

	assert.equal(input?.inferredRequirement, "required");
});

test("without caller evidence an ambient read stays unknown", () => {
	const analysis = analyzeNazareTheme([
		{ path: "sections/main.liquid", contents: `{% render 'card' %}` },
		{ path: "snippets/card.liquid", contents: "{{ product.title }}" },
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "product",
	);

	assert.equal(input?.inferredRequirement, "unknown");
});

test("a guarded ambient input is never claimed to be safely omitted", () => {
	// The guard may protect against absent page context rather than an omitted
	// argument, so caller evidence raises it only to unknown.
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'card', product: featured %}`,
		},
		{
			path: "snippets/card.liquid",
			contents: "{% if product %}{{ product.title }}{% endif %}",
		},
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "product",
	);

	assert.equal(input?.inferredRequirement, "unknown");
});

test("guarding a derived property does not mark its base name guarded", () => {
	// `{% if benefits %}` shows the file handles missing benefits, not a missing
	// product, so product stays required on the strength of its unguarded read.
	const analysis = analyzeNazareTheme([
		{
			path: "sections/main.liquid",
			contents: `{% render 'benefits', product: featured %}`,
		},
		{
			path: "snippets/benefits.liquid",
			contents:
				"{% assign list = product.metafields.custom.benefits.value %}{% if list != blank %}{{ list }}{% endif %}",
		},
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "product",
	);

	assert.equal(input?.inferredRequirement, "required");
});

test("a declared-required input the source falls back for is reported", () => {
	const analysis = analyzeNazareTheme([
		{
			path: "snippets/c-cta.liquid",
			contents: [
				"{% doc %}",
				"  @param {string} form_id - Unique form id",
				"  @param {string} title - Heading",
				"{% enddoc %}",
				"{% assign id = form_id | default: 'product-form' %}",
				"{% if title != blank %}<h2>{{ title }}</h2>{% endif %}",
				"<form id='{{ id }}'></form>",
			].join("\n"),
		},
	]);
	const fallbacks = analysis.issues.filter(
		(issue) => issue.code === "THEME_DOC_PARAM_FALLBACK",
	);

	assert.equal(fallbacks.length, 2);
	assert.equal(
		fallbacks.every((issue) => issue.severity === "info"),
		true,
	);
	// The message distinguishes a supplied default from a bare guard.
	assert.equal(
		fallbacks.some((issue) => issue.message.includes("fallback value")),
		true,
	);
	assert.equal(
		fallbacks.some((issue) => issue.message.includes("guarded")),
		true,
	);
});

test("a dispatcher snippet does not require inputs only its other branches read", () => {
	// The caller selects a branch by argument; reads in the branches it did not
	// select are no evidence that this call is missing something.
	const analysis = analyzeNazareTheme([
		{
			path: "sections/pdp.liquid",
			contents: `{% render 'widget', mode: 'stars', product: product %}`,
		},
		{
			path: "layout/theme.liquid",
			contents: `{% render 'widget', mode: 'script' %}`,
		},
		{
			path: "snippets/widget.liquid",
			contents:
				"{% if mode == 'script' %}<script></script>{% elsif mode == 'stars' %}<div>{{ product.id }}</div>{% endif %}",
		},
	]);
	const input = analysis.ir.expectedInputs.find(
		(candidate) => candidate.name === "product",
	);

	assert.equal(input?.inferredRequirement, "unknown");
	assert.equal(
		analysis.issues.some(
			(issue) => issue.code === "THEME_RENDER_ARGUMENT_MISSING",
		),
		false,
	);
});
